pipeline {
    agent any

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Display Files') {
            steps {
                sh 'pwd'
                sh 'ls -la'
            }
        }

        stage('Create ZIP') {
            steps {
                sh '''
                cd MyWebsite
                zip -r website.zip .
                '''
            }
        }

        stage('Upload to S3') {
            steps {
                sh '''
                aws s3 cp MyWebsite/website.zip s3://jenkins-codedeploy-25-06-2026/website.zip
                '''
            }
        }
    }
}
