pipeline {
    agent any

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Display Files') {
            steps {
                sh 'pwd'
                sh 'ls -la'
            }
        }

        stage('Create ZIP') {
            steps {
                sh '''
                cd MyWebsite
                zip -r website.zip .
                ls -lh website.zip
                '''
            }
        }
    }
}
